/**
 * Script de Setup do Banco de Dados
 * Execute: node setup-db.js
 * 
 * Este script cria as tabelas no Supabase usando a API REST
 */

require('dotenv').config();
const { createClient } = require('@supabase/supabase-js');

const supabaseUrl = process.env.SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!supabaseUrl || !supabaseKey) {
    console.error('Configure as variáveis de ambiente primeiro!');
    process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

async function createTables() {
    console.log('Criando tabelas no Supabase...\n');

    const tables = [
        {
            name: 'customers',
            sql: `
                CREATE TABLE IF NOT EXISTS public.customers (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id UUID NOT NULL,
                    nome TEXT NOT NULL,
                    documento TEXT,
                    whatsapp TEXT,
                    email TEXT,
                    logradouro TEXT,
                    numero TEXT,
                    complemento TEXT,
                    bairro TEXT,
                    cep TEXT,
                    uf TEXT,
                    cidade TEXT,
                    localizacao TEXT,
                    status TEXT DEFAULT 'Lead',
                    crop_id BIGINT,
                    data_aniversario DATE,
                    lembrete_aniversario BOOLEAN DEFAULT false,
                    created_at TIMESTAMPTZ DEFAULT NOW(),
                    updated_at TIMESTAMPTZ DEFAULT NOW()
                );
            `
        },
        {
            name: 'products',
            sql: `
                CREATE TABLE IF NOT EXISTS public.products (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id UUID NOT NULL,
                    nome TEXT NOT NULL,
                    quantidade INTEGER DEFAULT 0,
                    unidade TEXT,
                    custo DECIMAL(10,2),
                    comissao DECIMAL(5,2),
                    descricao TEXT,
                    created_at TIMESTAMPTZ DEFAULT NOW(),
                    updated_at TIMESTAMPTZ DEFAULT NOW()
                );
            `
        },
        {
            name: 'crops',
            sql: `
                CREATE TABLE IF NOT EXISTS public.crops (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id UUID NOT NULL,
                    nome TEXT NOT NULL,
                    observacoes TEXT,
                    cor TEXT,
                    created_at TIMESTAMPTZ DEFAULT NOW()
                );
            `
        },
        {
            name: 'orders',
            sql: `
                CREATE TABLE IF NOT EXISTS public.orders (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id UUID NOT NULL,
                    customer_id BIGINT,
                    numero_pedido TEXT NOT NULL,
                    valor_total DECIMAL(10,2) NOT NULL,
                    data DATE NOT NULL DEFAULT CURRENT_DATE,
                    status_pagamento TEXT DEFAULT 'pendente',
                    tipo_pagamento TEXT,
                    parcelas INTEGER DEFAULT 1,
                    items JSONB NOT NULL DEFAULT '[]'::jsonb,
                    parcelas_detalhes JSONB,
                    observacoes TEXT,
                    created_at TIMESTAMPTZ DEFAULT NOW(),
                    updated_at TIMESTAMPTZ DEFAULT NOW()
                );
            `
        },
        {
            name: 'interactions',
            sql: `
                CREATE TABLE IF NOT EXISTS public.interactions (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id UUID NOT NULL,
                    customer_id BIGINT,
                    order_id BIGINT,
                    tipo TEXT NOT NULL,
                    observacao TEXT,
                    data TIMESTAMPTZ DEFAULT NOW(),
                    metadata_ia JSONB DEFAULT '{}'::jsonb
                );
            `
        },
        {
            name: 'tasks',
            sql: `
                CREATE TABLE IF NOT EXISTS public.tasks (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id UUID NOT NULL,
                    customer_id BIGINT,
                    titulo TEXT NOT NULL,
                    data DATE,
                    prioridade TEXT DEFAULT 'media',
                    status TEXT DEFAULT 'pendente',
                    created_at TIMESTAMPTZ DEFAULT NOW(),
                    updated_at TIMESTAMPTZ DEFAULT NOW()
                );
            `
        }
    ];

    for (const table of tables) {
        try {
            console.log(`Criando tabela ${table.name}...`);
            // Note: Não podemos executar SQL diretamente via JS client
            // Este script é apenas informativo
            console.log(`  ⚠️  Execute o SQL manualmente no Supabase Dashboard`);
        } catch (error) {
            console.error(`  Erro: ${error.message}`);
        }
    }

    console.log('\n========================================');
    console.log('INFELIZMENTE, O SUPABASE JS CLIENT NÃO');
    console.log('PERMITE EXECUTAR SQL DIRETAMENTE.');
    console.log('========================================');
    console.log('\nPOR FAVOR, EXECUTE O SQL MANUALMENTE:');
    console.log('1. Acesse supabase.com/dashboard');
    console.log('2. Selecione seu projeto');
    console.log('3. Vá em SQL Editor');
    console.log('4. Execute o arquivo:');
    console.log('   supabase/migrations/001_initial_schema.sql');
    console.log('========================================\n');
}

createTables();