-- ============================================
-- CRM VENDAS - Schema do Banco de Dados
-- Supabase PostgreSQL com Row Level Security
-- ============================================
-- Execute este script no SQL Editor do Supabase
-- ============================================

-- ============================================
-- TABELAS
-- ============================================

-- Tabela de clientes
CREATE TABLE IF NOT EXISTS public.customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) NOT NULL,
    nome TEXT NOT NULL,
    documento TEXT,
    whatsapp TEXT,
    email TEXT,
    logradouro TEXT,
    numero TEXT,
    complemento TEXT,
    bairro TEXT,
    cep TEXT,
    uf TEXT,
    cidade TEXT,
    localizacao TEXT,
    status TEXT DEFAULT 'Lead' CHECK (status IN ('Lead', 'Prospect', 'Cliente', 'Inativo')),
    crop_id BIGINT,
    data_aniversario DATE,
    lembrete_aniversario BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabela de produtos
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) NOT NULL,
    nome TEXT NOT NULL,
    quantidade INTEGER DEFAULT 0,
    unidade TEXT,
    custo DECIMAL(10,2),
    comissao DECIMAL(5,2),
    descricao TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabela de culturas agrícolas
CREATE TABLE IF NOT EXISTS public.crops (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) NOT NULL,
    nome TEXT NOT NULL,
    observacoes TEXT,
    cor TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabela de pedidos
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) NOT NULL,
    customer_id BIGINT REFERENCES public.customers(id) ON DELETE CASCADE,
    numero_pedido TEXT UNIQUE NOT NULL,
    valor_total DECIMAL(10,2) NOT NULL,
    data DATE NOT NULL DEFAULT CURRENT_DATE,
    status_pagamento TEXT DEFAULT 'pendente' CHECK (status_pagamento IN ('pendente', 'pago', 'atrasado', 'cancelado')),
    tipo_pagamento TEXT,
    parcelas INTEGER DEFAULT 1,
    items JSONB NOT NULL DEFAULT '[]'::jsonb,
    parcelas_detalhes JSONB,
    observacoes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabela de interações (logs estruturados para IA)
CREATE TABLE IF NOT EXISTS public.interactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) NOT NULL,
    customer_id BIGINT REFERENCES public.customers(id) ON DELETE CASCADE,
    order_id BIGINT REFERENCES public.orders(id) ON DELETE SET NULL,
    tipo TEXT NOT NULL,
    observacao TEXT,
    data TIMESTAMPTZ DEFAULT NOW(),
    metadata_ia JSONB DEFAULT '{}'::jsonb
);

-- Tabela de tarefas
CREATE TABLE IF NOT EXISTS public.tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) NOT NULL,
    customer_id BIGINT REFERENCES public.customers(id) ON DELETE SET NULL,
    titulo TEXT NOT NULL,
    data DATE,
    prioridade TEXT DEFAULT 'media' CHECK (prioridade IN ('baixa', 'media', 'alta')),
    status TEXT DEFAULT 'pendente' CHECK (status IN ('pendente', 'concluida', 'cancelada')),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================
-- ROW LEVEL SECURITY (RLS)
-- ============================================

-- Habilitar RLS em todas as tabelas
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.crops ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.interactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;

-- ============================================
-- POLÍTICAS RLS
-- Cada usuário só vê/edita seus próprios dados
-- ============================================

-- Customers
DROP POLICY IF EXISTS "users_own_customers_select" ON public.customers;
DROP POLICY IF EXISTS "users_own_customers_insert" ON public.customers;
DROP POLICY IF EXISTS "users_own_customers_update" ON public.customers;
DROP POLICY IF EXISTS "users_own_customers_delete" ON public.customers;

CREATE POLICY "users_own_customers_select" ON public.customers FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "users_own_customers_insert" ON public.customers FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "users_own_customers_update" ON public.customers FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "users_own_customers_delete" ON public.customers FOR DELETE USING (auth.uid() = user_id);

-- Products
DROP POLICY IF EXISTS "users_own_products_select" ON public.products;
DROP POLICY IF EXISTS "users_own_products_insert" ON public.products;
DROP POLICY IF EXISTS "users_own_products_update" ON public.products;
DROP POLICY IF EXISTS "users_own_products_delete" ON public.products;

CREATE POLICY "users_own_products_select" ON public.products FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "users_own_products_insert" ON public.products FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "users_own_products_update" ON public.products FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "users_own_products_delete" ON public.products FOR DELETE USING (auth.uid() = user_id);

-- Crops
DROP POLICY IF EXISTS "users_own_crops_select" ON public.crops;
DROP POLICY IF EXISTS "users_own_crops_insert" ON public.crops;
DROP POLICY IF EXISTS "users_own_crops_update" ON public.crops;
DROP POLICY IF EXISTS "users_own_crops_delete" ON public.crops;

CREATE POLICY "users_own_crops_select" ON public.crops FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "users_own_crops_insert" ON public.crops FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "users_own_crops_update" ON public.crops FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "users_own_crops_delete" ON public.crops FOR DELETE USING (auth.uid() = user_id);

-- Orders
DROP POLICY IF EXISTS "users_own_orders_select" ON public.orders;
DROP POLICY IF EXISTS "users_own_orders_insert" ON public.orders;
DROP POLICY IF EXISTS "users_own_orders_update" ON public.orders;
DROP POLICY IF EXISTS "users_own_orders_delete" ON public.orders;

CREATE POLICY "users_own_orders_select" ON public.orders FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "users_own_orders_insert" ON public.orders FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "users_own_orders_update" ON public.orders FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "users_own_orders_delete" ON public.orders FOR DELETE USING (auth.uid() = user_id);

-- Interactions
DROP POLICY IF EXISTS "users_own_interactions_select" ON public.interactions;
DROP POLICY IF EXISTS "users_own_interactions_insert" ON public.interactions;
DROP POLICY IF EXISTS "users_own_interactions_update" ON public.interactions;
DROP POLICY IF EXISTS "users_own_interactions_delete" ON public.interactions;

CREATE POLICY "users_own_interactions_select" ON public.interactions FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "users_own_interactions_insert" ON public.interactions FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "users_own_interactions_update" ON public.interactions FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "users_own_interactions_delete" ON public.interactions FOR DELETE USING (auth.uid() = user_id);

-- Tasks
DROP POLICY IF EXISTS "users_own_tasks_select" ON public.tasks;
DROP POLICY IF EXISTS "users_own_tasks_insert" ON public.tasks;
DROP POLICY IF EXISTS "users_own_tasks_update" ON public.tasks;
DROP POLICY IF EXISTS "users_own_tasks_delete" ON public.tasks;

CREATE POLICY "users_own_tasks_select" ON public.tasks FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "users_own_tasks_insert" ON public.tasks FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "users_own_tasks_update" ON public.tasks FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "users_own_tasks_delete" ON public.tasks FOR DELETE USING (auth.uid() = user_id);

-- ============================================
-- ÍNDICES PARA PERFORMANCE
-- ============================================

CREATE INDEX IF NOT EXISTS idx_customers_user_id ON public.customers(user_id);
CREATE INDEX IF NOT EXISTS idx_customers_status ON public.customers(status);
CREATE INDEX IF NOT EXISTS idx_products_user_id ON public.products(user_id);
CREATE INDEX IF NOT EXISTS idx_crops_user_id ON public.crops(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_user_id ON public.orders(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_customer_id ON public.orders(customer_id);
CREATE INDEX IF NOT EXISTS idx_orders_status_pagamento ON public.orders(status_pagamento);
CREATE INDEX IF NOT EXISTS idx_interactions_user_id ON public.interactions(user_id);
CREATE INDEX IF NOT EXISTS idx_interactions_customer_id ON public.interactions(customer_id);
CREATE INDEX IF NOT EXISTS idx_tasks_user_id ON public.tasks(user_id);
CREATE INDEX IF NOT EXISTS idx_tasks_status ON public.tasks(status);

-- ============================================
-- DADOS INICIAIS (Seed Data)
-- ============================================

-- Função para inserir dados iniciais
CREATE OR REPLACE FUNCTION public.insert_initial_data()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    -- Inserir culturas padrão se não existirem
    INSERT INTO public.crops (user_id, nome, observacoes, cor)
    SELECT auth.uid(), 'Batata', 'Cultivo principal da região serrana', '#2563eb'
    WHERE NOT EXISTS (SELECT 1 FROM public.crops WHERE nome = 'Batata' AND user_id = auth.uid());
    
    INSERT INTO public.crops (user_id, nome, observacoes, cor)
    SELECT auth.uid(), 'Soja', 'Grão para exportação', '#16a34a'
    WHERE NOT EXISTS (SELECT 1 FROM public.crops WHERE nome = 'Soja' AND user_id = auth.uid());
    
    INSERT INTO public.crops (user_id, nome, observacoes, cor)
    SELECT auth.uid(), 'Café', 'Variedade arábica', '#ea580c'
    WHERE NOT EXISTS (SELECT 1 FROM public.crops WHERE nome = 'Café' AND user_id = auth.uid());
END;
$$;

-- ============================================
-- FUNÇÕES AUXILIARES
-- ============================================

-- Função para atualizar updated_at automaticamente
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Triggers para atualizar updated_at
CREATE TRIGGER update_customers_updated_at BEFORE UPDATE ON public.customers
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_products_updated_at BEFORE UPDATE ON public.products
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_orders_updated_at BEFORE UPDATE ON public.orders
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_tasks_updated_at BEFORE UPDATE ON public.tasks
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- ============================================
-- FUNÇÃO PARA GERAR NÚMERO DE PEDIDO
-- ============================================

CREATE OR REPLACE FUNCTION public.generate_order_number()
RETURNS TEXT AS $$
DECLARE
    prefixo TEXT := 'PED';
    ano TEXT;
    mes TEXT;
    dia TEXT;
    sequencial TEXT;
    numero TEXT;
BEGIN
    ano := TO_CHAR(NOW(), 'YY');
    mes := TO_CHAR(NOW(), 'MM');
    dia := TO_CHAR(NOW(), 'DD');
    
    -- Gera um número aleatório de 4 dígitos
    sequencial := LPAD(FLOOR(RANDOM() * 10000)::TEXT, 4, '0');
    
    numero := prefixo || ano || mes || dia || sequencial;
    
    -- Verifica se já existe, se existir gera novamente
    IF EXISTS (SELECT 1 FROM public.orders WHERE numero_pedido = numero) THEN
        sequencial := LPAD(FLOOR(RANDOM() * 10000)::TEXT, 4, '0');
        numero := prefixo || ano || mes || dia || sequencial;
    END IF;
    
    RETURN numero;
END;
$$ LANGUAGE plpgsql;

-- ============================================
-- PERMISSÕES
-- ============================================

-- Allow authenticated users to call the generate function
GRANT EXECUTE ON FUNCTION public.generate_order_number() TO authenticated;
GRANT EXECUTE ON FUNCTION public.insert_initial_data() TO authenticated;

-- ============================================
-- FIM DO SCRIPT
-- ============================================
-- Execute no SQL Editor do Supabase Dashboard
-- ============================================