-- ============================================
-- Tabela de Notificações
-- ============================================

CREATE TABLE IF NOT EXISTS public.notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) NOT NULL,
    titulo TEXT NOT NULL,
    mensagem TEXT NOT NULL,
    tipo TEXT NOT NULL CHECK (tipo IN (
        'parcela_vencendo',
        'parcela_vencida',
        'tarefa_pendente',
        'aniversario',
        'followup',
        'sistema'
    )),
    referencia_id BIGINT,
    referencia_tipo TEXT,
    lida BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "users_own_notifications_select" ON public.notifications;
DROP POLICY IF EXISTS "users_own_notifications_insert" ON public.notifications;
DROP POLICY IF EXISTS "users_own_notifications_delete" ON public.notifications;

CREATE POLICY "users_own_notifications_select" ON public.notifications FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "users_own_notifications_insert" ON public.notifications FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "users_own_notifications_delete" ON public.notifications FOR DELETE USING (auth.uid() = user_id);

-- Índices
CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON public.notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_lida ON public.notifications(user_id, lida);
CREATE INDEX IF NOT EXISTS idx_notifications_created_at ON public.notifications(created_at DESC);

-- Permissões para service role
GRANT ALL ON public.notifications TO service_role;

-- Função para criar notificação (chamada pelas edge functions)
CREATE OR REPLACE FUNCTION public.criar_notificacao(
    p_user_id UUID,
    p_titulo TEXT,
    p_mensagem TEXT,
    p_tipo TEXT,
    p_referencia_id BIGINT DEFAULT NULL,
    p_referencia_tipo TEXT DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    INSERT INTO public.notifications (user_id, titulo, mensagem, tipo, referencia_id, referencia_tipo)
    VALUES (p_user_id, p_titulo, p_mensagem, p_tipo, p_referencia_id, p_referencia_tipo);
END;
$$;

GRANT EXECUTE ON FUNCTION public.criar_notificacao TO service_role;